from __future__ import annotations

import re
from pathlib import Path

GAME = Path(__file__).resolve().parent / 'src/game.js'
text = GAME.read_text(encoding='utf-8')

replacement = r'''  staticBlocked(pos){const m=this.member,g=this.game,b=g.currentBounds();if(pos.x<-b.xMax+.5||pos.x>b.xMax-.5||pos.z<b.zMin+.5||pos.z>b.zMax-.5)return true;for(const o of g.obstacles)if(Math.abs(pos.x-o.x)<o.w/2+m.radius+.05&&Math.abs(pos.z-o.z)<o.d/2+m.radius+.05)return true;return false;}
  approachPoint(target){const m=this.member,pos=target?.pos||target?.group?.position;if(!pos||target.type==='storage')return pos;const o=this.game.obstacles.find(x=>x.type===target.type&&Math.abs(x.x-pos.x)<.08&&Math.abs(x.z-pos.z)<.08);if(!o)return pos;const pad=m.radius+.22,candidates=[new THREE.Vector3(o.x,0,o.z-o.d/2-pad),new THREE.Vector3(o.x+o.w/2+pad,0,o.z),new THREE.Vector3(o.x,0,o.z+o.d/2+pad),new THREE.Vector3(o.x-o.w/2-pad,0,o.z)];const valid=candidates.filter(p=>!this.staticBlocked(p)),pool=valid.length?valid:candidates;pool.sort((a,b)=>a.distanceToSquared(m.group.position)-b.distanceToSquared(m.group.position));return pool[0];}
  planPath(goal){const m=this.member,start=m.group.position.clone(),step=.38,gx=Math.round((goal.x-start.x)/step),gz=Math.round((goal.z-start.z)/step),key=(x,z)=>`${x},${z}`,dirs=[[1,0],[-1,0],[0,1],[0,-1]],open=new Map(),came=new Map(),cost=new Map(),nodes=new Map(),startKey=key(0,0);open.set(startKey,{x:0,z:0,f:Math.abs(gx)+Math.abs(gz)});cost.set(startKey,0);nodes.set(startKey,{x:0,z:0});let endKey=null;for(let iter=0;iter<2600&&open.size;iter++){let ck=null,cur=null;for(const[k,n]of open)if(!cur||n.f<cur.f){ck=k;cur=n;}open.delete(ck);if(Math.abs(cur.x-gx)+Math.abs(cur.z-gz)<=1){endKey=ck;break;}for(const[dX,dZ]of dirs){const nx=cur.x+dX,nz=cur.z+dZ,nk=key(nx,nz),p=new THREE.Vector3(start.x+nx*step,0,start.z+nz*step);if(this.staticBlocked(p))continue;const nc=(cost.get(ck)||0)+1;if(nc>=(cost.get(nk)??Infinity))continue;cost.set(nk,nc);came.set(nk,ck);nodes.set(nk,{x:nx,z:nz});open.set(nk,{x:nx,z:nz,f:nc+Math.abs(gx-nx)+Math.abs(gz-nz)});}}if(!endKey)return[goal.clone()];const rev=[];for(let k=endKey;k&&k!==startKey;k=came.get(k)){const n=nodes.get(k);if(!n)break;rev.push(new THREE.Vector3(start.x+n.x*step,0,start.z+n.z*step));}rev.reverse();if(!rev.length||rev[rev.length-1].distanceToSquared(goal)>.04)rev.push(goal.clone());return rev;}
  near(target,dt){const m=this.member,g=this.game,raw=target?.pos||target?.group?.position;if(!raw)return false;if(this.navTarget!==target){this.navTarget=target;this.navGoal=(this.approachPoint(target)||raw).clone();this.navPath=this.planPath(this.navGoal);this.navStall=0;}const goal=this.navGoal||raw;if(m.group.position.distanceTo(goal)<.26){m.animate(dt,false);return true;}while(this.navPath?.length&&m.group.position.distanceTo(this.navPath[0])<.2)this.navPath.shift();const wp=this.navPath?.[0]||goal,v=new THREE.Vector3(wp.x-m.group.position.x,0,wp.z-m.group.position.z);if(v.length()<.001){this.navPath?.shift();return false;}v.normalize();m.facing.copy(v);m.group.rotation.y=Math.atan2(v.x,v.z);const before=m.group.position.clone(),beforeGoal=before.distanceToSquared(goal);g.moveCrew(m,v.clone().multiplyScalar(m.speed*.9*dt));let moved=before.distanceToSquared(m.group.position)>1e-7;if(!moved){const side=new THREE.Vector3(-v.z,0,v.x).multiplyScalar(this.avoidSign);g.moveCrew(m,side.clone().multiplyScalar(m.speed*.62*dt));moved=before.distanceToSquared(m.group.position)>1e-7;if(!moved){this.avoidSign*=-1;g.moveCrew(m,side.multiplyScalar(-m.speed*.62*dt));moved=before.distanceToSquared(m.group.position)>1e-7;}}const afterGoal=m.group.position.distanceToSquared(goal);if(!moved||afterGoal>=beforeGoal-1e-5)this.navStall=(this.navStall||0)+dt;else this.navStall=0;if(this.navStall>.45){this.navPath=this.planPath(goal);this.navStall=0;this.avoidSign*=-1;}m.animate(dt,true,.95);return false;}
  update(dt){'''

pattern = re.compile(r"  approachPoint\(target\)\{.*?\n  update\(dt\)\{", re.S)
text, count = pattern.subn(replacement, text, count=1)
if count != 1:
    raise SystemExit(f'Expected to replace one V6 BotBrain navigation block, replaced {count}')
GAME.write_text(text, encoding='utf-8')
print('Applied V6 collision-aware A-star bot navigation.')
