const port=Number(process.env.CDP_PORT||9333);const endpoint=`http://127.0.0.1:${port}/json`;const gameUrl='http://127.0.0.1:8765/index.html';const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function waitPage(){for(let i=0;i<400;i++){try{const pages=await fetch(endpoint).then(r=>r.json());const p=pages.find(x=>x.type==='page');if(p)return p;}catch{}await sleep(100);}throw new Error('CDP page unavailable');}
class CDP{constructor(url){this.ws=new WebSocket(url);this.id=1;this.pending=new Map();this.exceptions=[];this.errors=[];this.ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.id&&this.pending.has(m.id)){const q=this.pending.get(m.id);this.pending.delete(m.id);m.error?q.reject(new Error(JSON.stringify(m.error))):q.resolve(m.result);}else if(m.method==='Runtime.exceptionThrown')this.exceptions.push(m.params?.exceptionDetails?.exception?.description||m.params?.exceptionDetails?.text||'Runtime exception');else if(m.method==='Runtime.consoleAPICalled'&&m.params?.type==='error')this.errors.push((m.params.args||[]).map(x=>x.value??x.description??'').join(' '));};}async open(){if(this.ws.readyState!==WebSocket.OPEN)await new Promise((r,j)=>{this.ws.onopen=r;this.ws.onerror=j;});}send(method,params={}){const id=this.id++;return new Promise((resolve,reject)=>{this.pending.set(id,{resolve,reject});this.ws.send(JSON.stringify({id,method,params}));});}async eval(expr){const r=await this.send('Runtime.evaluate',{expression:expr,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw new Error(r.exceptionDetails.exception?.description||r.exceptionDetails.text);return r.result?.value;}}
async function waitEval(cdp,expr,timeout=10000){const end=Date.now()+timeout;let last;while(Date.now()<end){try{last=await cdp.eval(expr);if(last)return last;}catch{}await sleep(100);}throw new Error(`Timeout: ${expr}; last=${JSON.stringify(last)}`);}
async function mouse(cdp,x,y,button='left',hold=80){await cdp.send('Input.dispatchMouseEvent',{type:'mouseMoved',x,y});await cdp.send('Input.dispatchMouseEvent',{type:'mousePressed',x,y,button,clickCount:1});await sleep(hold);await cdp.send('Input.dispatchMouseEvent',{type:'mouseReleased',x,y,button,clickCount:1});await sleep(180);}
async function key(cdp,code,keyValue,hold=650){await cdp.send('Input.dispatchKeyEvent',{type:'keyDown',code,key:keyValue});await sleep(hold);await cdp.send('Input.dispatchKeyEvent',{type:'keyUp',code,key:keyValue});await sleep(180);}
async function moveAndPoint(cdp,type,kind=null,y=1.0,offset=1.35){return cdp.eval(`(()=>{const g=window.__rkrGame,p=g.players[0],s=g.stations.find(x=>x.type===${JSON.stringify(type)}${kind?`&&x.kind===${JSON.stringify(kind)}`:''});if(!s)throw new Error('Station not found: ${type}${kind?':'+kind:''}');p.group.position.set(s.pos.x,0,s.pos.z+${offset});g.cameraRig.update(.7);const v=s.pos.clone();v.y=${y};v.project(g.camera);const r=g.canvas.getBoundingClientRect();return{x:r.left+(v.x+1)*r.width/2,y:r.top+(1-v.y)*r.height/2,station:{x:s.pos.x,z:s.pos.z},player:{x:p.group.position.x,z:p.group.position.z}};})()`);}

const page=await waitPage(),cdp=new CDP(page.webSocketDebuggerUrl);await cdp.open();await cdp.send('Runtime.enable');await cdp.send('Page.enable');await cdp.send('Page.navigate',{url:gameUrl});await waitEval(cdp,`document.readyState==='complete'&&!!window.__rkrGame?.__seniorV9`,15000);await cdp.eval(`localStorage.clear();true`);await cdp.send('Page.reload',{ignoreCache:true});await waitEval(cdp,`document.readyState==='complete'&&!!window.__rkrGame?.__seniorV9`,15000);cdp.exceptions.length=0;cdp.errors.length=0;

const setup=await cdp.eval(`(()=>{const g=window.__rkrGame;g.config.humanCount=1;g.config.roles=['chef','prep','service'];g.config.menu=['salad','burger'];g.business.cash=500;g.business.plan=[];g.plan=[];g.enterBuildMode();g.autoLayout();const plan=g.plan.map(q=>({key:q.key,x:q.x,z:q.z}));g.openRestaurant();g.spawnTimer=9999;g.timeLeft=9999;g.__seniorV9.applyPointerOwnership?.();return{version:g.__seniorV9.version,patch:g.__seniorV9.patchLevel,players:g.players.length,bots:g.players.filter(p=>!p.human).length,plan,overlay:document.getElementById('v9-input-layer').classList.contains('active'),canvas:getComputedStyle(g.canvas).pointerEvents,actionCard:getComputedStyle(document.getElementById('v8-action-card')).display};})()`);
if(setup.version!=='9.0.0'||setup.players!==1||setup.bots!==0||!setup.overlay||setup.canvas!=='none'||setup.actionCard!=='none')throw new Error(`V9 service ownership/solo setup failed: ${JSON.stringify(setup)}`);if(!setup.plan.some(x=>x.key==='grocery')||!setup.plan.some(x=>x.key==='prep')||!setup.plan.some(x=>x.key==='stove')||setup.plan.filter(x=>x.key==='table').length<2)throw new Error(`V9 work-triangle layout incomplete: ${JSON.stringify(setup.plan)}`);

const plate=await moveAndPoint(cdp,'plate');await mouse(cdp,plate.x,plate.y,'left');await waitEval(cdp,`!!window.__rkrGame.players[0].held?.isPlate`,4000);const plateResult=await cdp.eval(`(()=>{const g=window.__rkrGame,p=g.players[0];return{held:p.held?.description?.(),task:!!g.__seniorV9.state.task,starts:g.qaEvents.filter(e=>e.type==='v9-task-start').length,done:g.qaEvents.filter(e=>e.type==='v9-task-complete').length};})()`);if(plateResult.held!=='plate'||plateResult.task||plateResult.done<1)throw new Error(`Real left-click plate pickup failed: ${JSON.stringify({plate,plateResult})}`);await cdp.eval(`(()=>{const p=window.__rkrGame.players[0];p.held?.dispose();p.held=null;return true;})()`);

const tomato=await moveAndPoint(cdp,'storage','tomato',1.05,.85);const stock0=await cdp.eval(`window.__rkrGame.v8Stock.tomato`);await mouse(cdp,tomato.x,tomato.y,'right');await sleep(300);const cancelled=await cdp.eval(`(()=>{const g=window.__rkrGame,p=g.players[0];return{held:p.held?.kind||null,stock:g.v8Stock.tomato,task:!!g.__seniorV9.state.task,cancels:g.qaEvents.filter(e=>e.type==='v9-right-cancel').length};})()`);if(cancelled.held!==null||cancelled.stock!==stock0||cancelled.task||cancelled.cancels<1)throw new Error(`Right click performed work instead of cancellation: ${JSON.stringify(cancelled)}`);

const tomato2=await moveAndPoint(cdp,'storage','tomato',1.05,.85);await mouse(cdp,tomato2.x,tomato2.y,'left');await waitEval(cdp,`window.__rkrGame.players[0].held?.kind==='tomato'`,4000);const tomatoResult=await cdp.eval(`(()=>{const g=window.__rkrGame,p=g.players[0];return{held:p.held?.kind,state:p.held?.state,stock:g.v8Stock.tomato};})()`);if(tomatoResult.state!=='raw'||tomatoResult.stock!==stock0-1)throw new Error(`Real left-click grocery pickup failed: ${JSON.stringify({tomato2,tomatoResult,stock0})}`);

const prep=await moveAndPoint(cdp,'prep');await mouse(cdp,prep.x,prep.y,'left');await waitEval(cdp,`window.__rkrGame.players[0].held?.kind==='tomato'&&window.__rkrGame.players[0].held?.state==='chopped'`,8000);const prepResult=await cdp.eval(`(()=>{const g=window.__rkrGame,p=g.players[0],s=g.stations.find(x=>x.type==='prep');return{held:p.held?.kind,state:p.held?.state,slot:s.slot?.kind||null,task:!!g.__seniorV9.state.task,done:g.qaEvents.filter(e=>e.type==='v9-task-complete'&&e.target==='prep').length};})()`);if(prepResult.state!=='chopped'||prepResult.slot!==null||prepResult.task||prepResult.done<1)throw new Error(`Single-click timed prep failed: ${JSON.stringify(prepResult)}`);

await cdp.eval(`(()=>{const g=window.__rkrGame,p=g.players[0],s=g.stations.find(x=>x.type==='counter');g.__seniorV9.queueTask(p,s);return true;})()`);const cancelPoint=await moveAndPoint(cdp,'prep');await mouse(cdp,cancelPoint.x,cancelPoint.y,'right');const cancelHeld=await cdp.eval(`(()=>{const g=window.__rkrGame,p=g.players[0];return{task:!!g.__seniorV9.state.task,held:p.held?.kind,state:p.held?.state};})()`);if(cancelHeld.task||cancelHeld.held!=='tomato'||cancelHeld.state!=='chopped')throw new Error(`Cancel changed held ingredient: ${JSON.stringify(cancelHeld)}`);

const npc=await cdp.eval(`(()=>{const g=window.__rkrGame;g.spawnParty();const p=g.parties.at(-1);return p?{hasV8:!!p.v8,bubble:!!p.v8?.bubble,trait:p.v8?.traits,customers:p.customers.length}:null;})()`);if(!npc||!npc.hasV8||!npc.bubble||npc.customers<1)throw new Error(`NPC systems regressed: ${JSON.stringify(npc)}`);const management=await cdp.eval(`(()=>{const g=window.__rkrGame;g.updateUI();return{clean:g.__seniorV8.cleanliness(),board:document.getElementById('v8-service-board').textContent,statuses:g.__seniorV9.stationStatus()};})()`);if(!management.board.includes('CLEANLINESS')||management.clean<0||management.clean>100||!Array.isArray(management.statuses))throw new Error(`Management systems regressed: ${JSON.stringify(management)}`);

const roster=await cdp.eval(`(()=>{const g=window.__rkrGame;g.config.humanCount=3;g.restartService();g.spawnTimer=9999;g.timeLeft=9999;const b=g.currentBounds();const free=(p,x,z)=>{if(x<-b.xMax+.65||x>b.xMax-.65||z<b.zMin+.65||z>b.zMax-.65)return false;for(const o of g.obstacles)if(Math.abs(x-o.x)<o.w/2+p.radius+.1&&Math.abs(z-o.z)<o.d/2+p.radius+.1)return false;return true;};const lane=(p,dx,dz)=>{for(let z=Math.max(b.zMin+1,-.3);z<=Math.min(b.zMax-1,1.5);z+=.35)for(let x=-b.xMax+1;x<=b.xMax-1;x+=.4)if(free(p,x,z)&&free(p,x+dx,z+dz))return{x,z};return null;};return{players:g.players.length,bots:g.players.filter(p=>!p.human).length,l2:lane(g.players[1],1.2,0),l3:lane(g.players[2],0,1.2)};})()`);if(roster.players!==3||roster.bots!==0||!roster.l2||!roster.l3)throw new Error(`Three-player roster regression: ${JSON.stringify(roster)}`);
await cdp.eval(`(()=>{const g=window.__rkrGame,l=${JSON.stringify(roster.l2)};g.players[0].group.position.set(99,0,99);g.players[2].group.position.set(-99,0,-99);g.players[1].group.position.set(l.x,0,l.z);return true;})()`);const p2a=await cdp.eval(`window.__rkrGame.players[1].group.position.x`);await key(cdp,'KeyD','d');const p2b=await cdp.eval(`window.__rkrGame.players[1].group.position.x`);if(!(p2b>p2a+.18))throw new Error(`P2 WASD failed ${p2a}->${p2b}`);
await cdp.eval(`(()=>{const g=window.__rkrGame,l=${JSON.stringify(roster.l3)};g.players[0].group.position.set(99,0,99);g.players[1].group.position.set(-99,0,-99);g.players[2].group.position.set(l.x,0,l.z);return true;})()`);const p3a=await cdp.eval(`window.__rkrGame.players[2].group.position.z`);await key(cdp,'ArrowDown','ArrowDown');const p3b=await cdp.eval(`window.__rkrGame.players[2].group.position.z`);if(!(p3b>p3a+.18))throw new Error(`P3 arrows failed ${p3a}->${p3b}`);

const build=await cdp.eval(`(()=>{const g=window.__rkrGame;g.enterBuildMode();g.__seniorV9.applyPointerOwnership?.();return{state:g.state,canvas:getComputedStyle(g.canvas).pointerEvents,overlay:document.getElementById('v9-input-layer').classList.contains('active')};})()`);if(build.state!=='build'||build.canvas!=='auto'||build.overlay)throw new Error(`Build pointer/camera restoration failed: ${JSON.stringify(build)}`);
if(cdp.exceptions.length)throw new Error(`Runtime exceptions: ${cdp.exceptions.join(' | ')}`);if(cdp.errors.length)throw new Error(`Console errors: ${cdp.errors.join(' | ')}`);console.log('Senior V9 real-browser E2E passed',JSON.stringify({setup,plateResult,cancelled,tomatoResult,prepResult,cancelHeld,npc,management,roster,p2a,p2b,p3a,p3b,build}));cdp.ws.close();
