const port=Number(process.env.CDP_PORT||9333);const endpoint=`http://127.0.0.1:${port}/json`;const gameUrl='http://127.0.0.1:8765/index.html';const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function waitForPage(){for(let i=0;i<400;i++){try{const pages=await fetch(endpoint).then(r=>r.json());const page=pages.find(p=>p.type==='page');if(page)return page;}catch{}await sleep(100);}throw new Error('Chrome DevTools page did not become available');}
class CDP{constructor(url){this.ws=new WebSocket(url);this.next=1;this.pending=new Map();this.exceptions=[];this.consoleErrors=[];this.ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.id&&this.pending.has(m.id)){const{resolve,reject}=this.pending.get(m.id);this.pending.delete(m.id);m.error?reject(new Error(JSON.stringify(m.error))):resolve(m.result);}else if(m.method==='Runtime.exceptionThrown')this.exceptions.push(m.params?.exceptionDetails?.exception?.description||m.params?.exceptionDetails?.text||'Runtime exception');else if(m.method==='Runtime.consoleAPICalled'&&m.params?.type==='error')this.consoleErrors.push((m.params.args||[]).map(x=>x.value??x.description??'').join(' '));};}async open(){if(this.ws.readyState!==WebSocket.OPEN)await new Promise((resolve,reject)=>{this.ws.onopen=resolve;this.ws.onerror=reject;});}send(method,params={}){const id=this.next++;return new Promise((resolve,reject)=>{this.pending.set(id,{resolve,reject});this.ws.send(JSON.stringify({id,method,params}));});}async eval(expression){const r=await this.send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw new Error(r.exceptionDetails.exception?.description||r.exceptionDetails.text||'Evaluation failed');return r.result?.value;}}
async function waitEval(cdp,expression,timeout=10000){const end=Date.now()+timeout;let last;while(Date.now()<end){try{last=await cdp.eval(expression);if(last)return last;}catch{}await sleep(100);}throw new Error(`Timed out waiting for ${expression}; last=${JSON.stringify(last)}`);}
async function click(cdp,x,y,button='left',hold=75){await cdp.send('Input.dispatchMouseEvent',{type:'mouseMoved',x,y});await cdp.send('Input.dispatchMouseEvent',{type:'mousePressed',x,y,button,clickCount:1});await sleep(hold);await cdp.send('Input.dispatchMouseEvent',{type:'mouseReleased',x,y,button,clickCount:1});await sleep(180);}
async function key(cdp,code,keyValue,hold=650){await cdp.send('Input.dispatchKeyEvent',{type:'keyDown',code,key:keyValue});await sleep(hold);await cdp.send('Input.dispatchKeyEvent',{type:'keyUp',code,key:keyValue});await sleep(180);}

const page=await waitForPage(),cdp=new CDP(page.webSocketDebuggerUrl);await cdp.open();await cdp.send('Runtime.enable');await cdp.send('Page.enable');await cdp.send('Page.navigate',{url:gameUrl});await waitEval(cdp,`document.readyState==='complete'&&!!window.__rkrGame?.__seniorV9`,15000);await cdp.eval(`localStorage.clear();true`);await cdp.send('Page.reload',{ignoreCache:true});await waitEval(cdp,`document.readyState==='complete'&&!!window.__rkrGame?.__seniorV9`,15000);cdp.exceptions.length=0;cdp.consoleErrors.length=0;

const setup=await cdp.eval(`(()=>{const g=window.__rkrGame;g.config.humanCount=1;g.config.roles=['chef','prep','service'];g.config.menu=['salad','burger'];g.business.cash=500;g.business.plan=[];g.plan=[];g.enterBuildMode();g.autoLayout();const plan=g.plan.map(q=>({key:q.key,x:q.x,z:q.z}));g.openRestaurant();g.spawnTimer=9999;g.timeLeft=9999;return{v9:g.__seniorV9.version,players:g.players.length,bots:g.players.filter(p=>!p.human).length,plan,overlay:document.getElementById('v9-input-layer')?.classList.contains('active'),canvasPointer:getComputedStyle(g.canvas).pointerEvents,actionCard:getComputedStyle(document.getElementById('v8-action-card')).display};})()`);
if(setup.v9!=='9.0.0'||setup.players!==1||setup.bots!==0||!setup.overlay||setup.canvasPointer!=='none'||setup.actionCard!=='none')throw new Error(`V9 setup failed: ${JSON.stringify(setup)}`);
if(!setup.plan.some(q=>q.key==='grocery')||!setup.plan.some(q=>q.key==='prep')||!setup.plan.some(q=>q.key==='stove')||setup.plan.filter(q=>q.key==='table').length<2)throw new Error(`V9 layout incomplete: ${JSON.stringify(setup.plan)}`);

async function stationPoint(type,kind=null,y=1.0){return cdp.eval(`(()=>{const g=window.__rkrGame,s=g.stations.find(x=>x.type===${JSON.stringify(type)}${kind?`&&x.kind===${JSON.stringify(kind)}`:''});const v=s.pos.clone();v.y=${y};v.project(g.camera);const r=g.canvas.getBoundingClientRect();return{x:r.left+(v.x+1)*r.width/2,y:r.top+(1-v.y)*r.height/2,pos:{x:s.pos.x,z:s.pos.z}};})()`);}

const plate=await stationPoint('plate',null,1.0);await cdp.eval(`(()=>{const g=window.__rkrGame,p=g.players[0],s=g.stations.find(x=>x.type==='plate');p.group.position.set(s.pos.x,0,s.pos.z+1.35);g.cameraRig.update(.4);return true;})()`);await click(cdp,plate.x,plate.y,'left');await waitEval(cdp,`!!window.__rkrGame.players[0].held?.isPlate`,3000);const plateResult=await cdp.eval(`(()=>{const g=window.__rkrGame,p=g.players[0];return{held:p.held?.description?.(),task:!!g.__seniorV9.state.task,events:g.qaEvents.filter(e=>e.type==='v9-task-complete').length};})()`);if(plateResult.held!=='plate'||plateResult.task||plateResult.events<1)throw new Error(`V9 left-click plate action failed: ${JSON.stringify(plateResult)}`);await cdp.eval(`(()=>{const p=window.__rkrGame.players[0];p.held?.dispose();p.held=null;return true;})()`);

const tomato=await stationPoint('storage','tomato',1.05);await cdp.eval(`(()=>{const g=window.__rkrGame,p=g.players[0],s=g.stations.find(x=>x.type==='storage'&&x.kind==='tomato');p.group.position.set(s.pos.x,0,s.pos.z+.85);g.cameraRig.update(.4);return true;})()`);const stock0=await cdp.eval(`window.__rkrGame.v8Stock.tomato`);await click(cdp,tomato.x,tomato.y,'right',90);await sleep(250);const right=await cdp.eval(`(()=>{const g=window.__rkrGame,p=g.players[0];return{held:p.held?.kind||null,stock:g.v8Stock.tomato,task:!!g.__seniorV9.state.task,cancels:g.qaEvents.filter(e=>e.type==='v9-right-cancel').length};})()`);if(right.held!==null||right.stock!==stock0||right.task||right.cancels<1)throw new Error(`V9 right-click must be cancellation only: ${JSON.stringify(right)}`);

await click(cdp,tomato.x,tomato.y,'left');await waitEval(cdp,`window.__rkrGame.players[0].held?.kind==='tomato'`,3000);const tomatoResult=await cdp.eval(`(()=>{const g=window.__rkrGame,p=g.players[0];return{held:p.held?.kind,state:p.held?.state,stock:g.v8Stock.tomato};})()`);if(tomatoResult.state!=='raw'||tomatoResult.stock!==stock0-1)throw new Error(`V9 tomato pickup failed: ${JSON.stringify(tomatoResult)}`);

const prep=await stationPoint('prep',null,1.0);await cdp.eval(`(()=>{const g=window.__rkrGame,p=g.players[0],s=g.stations.find(x=>x.type==='prep');p.group.position.set(s.pos.x,0,s.pos.z+1.35);g.cameraRig.update(.4);return true;})()`);await click(cdp,prep.x,prep.y,'left');await waitEval(cdp,`window.__rkrGame.players[0].held?.kind==='tomato'&&window.__rkrGame.players[0].held?.state==='chopped'`,7000);const prepResult=await cdp.eval(`(()=>{const g=window.__rkrGame,p=g.players[0],s=g.stations.find(x=>x.type==='prep');return{held:p.held?.kind,state:p.held?.state,slot:s.slot?.kind||null,task:!!g.__seniorV9.state.task,workEvents:g.qaEvents.filter(e=>e.type==='v9-task-complete'&&e.target==='prep').length};})()`);if(prepResult.state!=='chopped'||prepResult.slot!==null||prepResult.task||prepResult.workEvents<1)throw new Error(`V9 automatic prep failed: ${JSON.stringify(prepResult)}`);

await cdp.eval(`(()=>{const g=window.__rkrGame,p=g.players[0],s=g.stations.find(x=>x.type==='counter');g.__seniorV9.queueTask(p,s);return true;})()`);await click(cdp,prep.x,prep.y,'right');const cancelResult=await cdp.eval(`(()=>{const g=window.__rkrGame,p=g.players[0];return{task:!!g.__seniorV9.state.task,held:p.held?.kind,state:p.held?.state};})()`);if(cancelResult.task||cancelResult.held!=='tomato'||cancelResult.state!=='chopped')throw new Error(`Right cancel altered carried item: ${JSON.stringify(cancelResult)}`);

const npc=await cdp.eval(`(()=>{const g=window.__rkrGame;g.spawnParty();const p=g.parties.at(-1);return p?{state:p.state,hasV8:!!p.v8,bubble:!!p.v8?.bubble,trait:p.v8?.traits,customers:p.customers.length}:null;})()`);if(!npc||!npc.hasV8||!npc.bubble||npc.customers<1)throw new Error(`V8 NPC/business systems regressed under V9: ${JSON.stringify(npc)}`);
const board=await cdp.eval(`(()=>{const g=window.__rkrGame;g.updateUI();const statuses=g.__seniorV9.stationStatus();return{text:document.getElementById('v8-service-board').textContent,statuses};})()`);if(!board.text.includes('CLEANLINESS')||!Array.isArray(board.statuses))throw new Error(`V9 management board regression: ${JSON.stringify(board)}`);

const roster=await cdp.eval(`(()=>{const g=window.__rkrGame;g.config.humanCount=3;g.restartService();g.spawnTimer=9999;g.timeLeft=9999;const b=g.currentBounds();const free=(p,x,z)=>{if(x<-b.xMax+.65||x>b.xMax-.65||z<b.zMin+.65||z>b.zMax-.65)return false;for(const o of g.obstacles)if(Math.abs(x-o.x)<o.w/2+p.radius+.1&&Math.abs(z-o.z)<o.d/2+p.radius+.1)return false;return true;};const lane=(p,dx,dz)=>{for(let z=Math.max(b.zMin+1,-.3);z<=Math.min(b.zMax-1,1.5);z+=.35)for(let x=-b.xMax+1;x<=b.xMax-1;x+=.4)if(free(p,x,z)&&free(p,x+dx,z+dz))return{x,z};return null;};return{players:g.players.length,bots:g.players.filter(p=>!p.human).length,l2:lane(g.players[1],1.2,0),l3:lane(g.players[2],0,1.2)};})()`);if(roster.players!==3||roster.bots!==0||!roster.l2||!roster.l3)throw new Error(`V9 three-player roster failed: ${JSON.stringify(roster)}`);
await cdp.eval(`(()=>{const g=window.__rkrGame,l=${JSON.stringify(roster.l2)};g.players[0].group.position.set(99,0,99);g.players[2].group.position.set(-99,0,-99);g.players[1].group.position.set(l.x,0,l.z);return true;})()`);const p2a=await cdp.eval(`window.__rkrGame.players[1].group.position.x`);await key(cdp,'KeyD','d');const p2b=await cdp.eval(`window.__rkrGame.players[1].group.position.x`);if(!(p2b>p2a+.18))throw new Error(`P2 movement regressed: ${p2a}->${p2b}`);
await cdp.eval(`(()=>{const g=window.__rkrGame,l=${JSON.stringify(roster.l3)};g.players[0].group.position.set(99,0,99);g.players[1].group.position.set(-99,0,-99);g.players[2].group.position.set(l.x,0,l.z);return true;})()`);const p3a=await cdp.eval(`window.__rkrGame.players[2].group.position.z`);await key(cdp,'ArrowDown','ArrowDown');const p3b=await cdp.eval(`window.__rkrGame.players[2].group.position.z`);if(!(p3b>p3a+.18))throw new Error(`P3 movement regressed: ${p3a}->${p3b}`);

await cdp.eval(`(()=>{const g=window.__rkrGame;g.enterBuildMode();return true;})()`);await sleep(200);const buildInput=await cdp.eval(`(()=>({state:window.__rkrGame.state,canvas:getComputedStyle(window.__rkrGame.canvas).pointerEvents,overlay:document.getElementById('v9-input-layer').classList.contains('active')}))()`);if(buildInput.state!=='build'||buildInput.canvas!=='auto'||buildInput.overlay)throw new Error(`Build-mode pointer restoration failed: ${JSON.stringify(buildInput)}`);

if(cdp.exceptions.length)throw new Error(`Runtime exceptions: ${cdp.exceptions.join(' | ')}`);if(cdp.consoleErrors.length)throw new Error(`Console errors: ${cdp.consoleErrors.join(' | ')}`);console.log('Senior V9 deterministic browser E2E passed',JSON.stringify({setup,plateResult,right,tomatoResult,prepResult,cancelResult,npc,board,roster,p2a,p2b,p3a,p3b,buildInput}));cdp.ws.close();
