const port=Number(process.env.CDP_PORT||9333),endpoint=`http://127.0.0.1:${port}/json`,sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function page(){for(let i=0;i<300;i++){try{const p=(await fetch(endpoint).then(r=>r.json())).find(x=>x.type==='page');if(p)return p;}catch{}await sleep(100);}throw new Error('no page');}
class C{constructor(url){this.ws=new WebSocket(url);this.id=1;this.p=new Map();this.ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.id&&this.p.has(m.id)){const q=this.p.get(m.id);this.p.delete(m.id);m.error?q.j(m.error):q.r(m.result);}};}async open(){if(this.ws.readyState!==1)await new Promise((r,j)=>{this.ws.onopen=r;this.ws.onerror=j;});}send(method,params={}){const id=this.id++;return new Promise((r,j)=>{this.p.set(id,{r,j});this.ws.send(JSON.stringify({id,method,params}));});}async eval(x){const r=await this.send('Runtime.evaluate',{expression:x,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw new Error(r.exceptionDetails.text);return r.result?.value;}}
async function click(c,x,y,button='left'){await c.send('Input.dispatchMouseEvent',{type:'mouseMoved',x,y});await c.send('Input.dispatchMouseEvent',{type:'mousePressed',x,y,button,clickCount:1});await sleep(80);await c.send('Input.dispatchMouseEvent',{type:'mouseReleased',x,y,button,clickCount:1});await sleep(150);}
async function pt(c,type,kind=null,offset=1.35,y=1){return c.eval(`(()=>{const g=window.__rkrGame,p=g.players[0],s=g.stations.find(x=>x.type===${JSON.stringify(type)}${kind?`&&x.kind===${JSON.stringify(kind)}`:''});p.group.position.set(s.pos.x,0,s.pos.z+${offset});g.cameraRig.update(.8);const v=s.pos.clone();v.y=${y};v.project(g.camera);const r=g.canvas.getBoundingClientRect();return{x:r.left+(v.x+1)*r.width/2,y:r.top+(1-v.y)*r.height/2};})()`);}
const p=await page(),c=new C(p.webSocketDebuggerUrl);await c.open();await c.send('Runtime.enable');await c.send('Page.enable');await c.send('Page.navigate',{url:'http://127.0.0.1:8765/index.html'});for(let i=0;i<150;i++){if(await c.eval(`document.readyState==='complete'&&!!window.__rkrGame?.__seniorV9`))break;await sleep(100);}await c.eval(`(()=>{const g=window.__rkrGame;localStorage.clear();g.config.humanCount=1;g.config.menu=['salad','burger'];g.business.plan=[];g.plan=[];g.enterBuildMode();g.autoLayout();g.openRestaurant();g.spawnTimer=999;g.timeLeft=999;return true;})()`);
const tomato=await pt(c,'storage','tomato',.85,1.05);await click(c,tomato.x,tomato.y);await sleep(500);console.log('AFTER TOMATO',JSON.stringify(await c.eval(`(()=>{const g=window.__rkrGame,p=g.players[0];return{held:p.held?.kind,state:p.held?.state,task:g.__seniorV9.state.task&&{type:g.__seniorV9.state.task.target?.type,kind:g.__seniorV9.state.task.target?.kind,phase:g.__seniorV9.state.task.phase},tail:g.qaEvents.slice(-8)};})()`)));
const prep=await pt(c,'prep');console.log('PREP POINT',JSON.stringify(prep));console.log('RESOLVE AT PREP',JSON.stringify(await c.eval(`(()=>{const g=window.__rkrGame,r=g.canvas.getBoundingClientRect(),e={clientX:${prep.x},clientY:${prep.y}},p=g.players[0],t=g.__seniorV9.resolveTarget(e,p);return{type:t?.type,kind:t?.kind,held:p.held?.kind,player:{x:p.group.position.x,z:p.group.position.z},prep:g.stations.find(x=>x.type==='prep').pos};})()`)));await click(c,prep.x,prep.y);for(const ms of[100,500,1500,3000]){await sleep(ms);console.log(`AFTER PREP +${ms}`,JSON.stringify(await c.eval(`(()=>{const g=window.__rkrGame,p=g.players[0],s=g.stations.find(x=>x.type==='prep'),t=g.__seniorV9.state.task;return{held:p.held&&{kind:p.held.kind,state:p.held.state},task:t&&{type:t.target?.type,kind:t.target?.kind,phase:t.phase,progress:t.progress},slot:s.slot&&{kind:s.slot.kind,state:s.slot.state},stationProgress:s.progress,tail:g.qaEvents.slice(-12)};})()`)));}
c.ws.close();
