const port = Number(process.env.CDP_PORT || 9333);
const endpoint = `http://127.0.0.1:${port}/json`;
const sleep = ms => new Promise(r => setTimeout(r, ms));

async function waitForPage(){for(let i=0;i<140;i++){try{const pages=await fetch(endpoint).then(r=>r.json());const page=pages.find(p=>p.type==='page'&&p.url.includes('127.0.0.1'));if(page)return page;}catch{}await sleep(100);}throw new Error('Chrome DevTools page did not become available');}
class CDP{constructor(url){this.ws=new WebSocket(url);this.next=1;this.pending=new Map();this.exceptions=[];this.consoleErrors=[];this.ws.onmessage=e=>{const msg=JSON.parse(e.data);if(msg.id&&this.pending.has(msg.id)){const{resolve,reject}=this.pending.get(msg.id);this.pending.delete(msg.id);msg.error?reject(new Error(JSON.stringify(msg.error))):resolve(msg.result);}else if(msg.method==='Runtime.exceptionThrown')this.exceptions.push(msg.params?.exceptionDetails?.exception?.description||msg.params?.exceptionDetails?.text||'Runtime exception');else if(msg.method==='Runtime.consoleAPICalled'&&msg.params?.type==='error')this.consoleErrors.push((msg.params.args||[]).map(x=>x.value??x.description??'').join(' '));};}async open(){if(this.ws.readyState!==WebSocket.OPEN)await new Promise((resolve,reject)=>{this.ws.onopen=resolve;this.ws.onerror=reject;});}send(method,params={}){const id=this.next++;return new Promise((resolve,reject)=>{this.pending.set(id,{resolve,reject});this.ws.send(JSON.stringify({id,method,params}));});}async eval(expression){const result=await this.send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(result.exceptionDetails)throw new Error(result.exceptionDetails.exception?.description||result.exceptionDetails.text||'Evaluation failed');return result.result?.value;}}

const page=await waitForPage();const cdp=new CDP(page.webSocketDebuggerUrl);await cdp.open();await cdp.send('Runtime.enable');await cdp.send('Page.enable');
for(let i=0;i<120;i++){if(await cdp.eval(`document.readyState==='complete'&&!!document.getElementById('start-btn')&&!!window.__rkrGame`))break;await sleep(100);}

const preflight=await cdp.eval(`(()=>{const canvas=document.getElementById('game-canvas'),g=window.__rkrGame;return{title:document.title,start:!!document.getElementById('start-btn'),webgl:!!(canvas&&(canvas.getContext('webgl2')||canvas.getContext('webgl'))),tier:g.business.expansionTier,bounds:g.currentBounds().xMax,cash:g.business.cash,sat:g.business.satisfaction,tableCap:g.tier().tableCap,customerCap:g.tier().customerCap,menuSlots:g.tier().menuSlots};})()`);
if(!preflight.start||!preflight.webgl||preflight.tier!==0||preflight.bounds>8||preflight.tableCap!==2||preflight.customerCap!==2||preflight.menuSlots!==2)throw new Error(`Progressive preflight failed: ${JSON.stringify(preflight)}`);

await cdp.eval(`document.getElementById('start-btn').click()`);await sleep(350);
const crew=await cdp.eval(`(()=>({visible:getComputedStyle(document.getElementById('crew-screen')).display!=='none',slots:document.querySelectorAll('#crew-slots .crew-slot').length,bots:document.querySelectorAll('#crew-slots .crew-slot.bot').length,activeMenu:document.querySelectorAll('#menu-toggle-grid .menu-toggle.active').length,lockedMenu:document.querySelectorAll('#menu-toggle-grid .menu-toggle.locked').length,business:document.getElementById('business-preview').textContent}))()`);
if(!crew.visible||crew.slots!==3||crew.bots!==2||crew.activeMenu!==2||crew.lockedMenu<4)throw new Error(`Starter crew/menu limits failed: ${JSON.stringify(crew)}`);

await cdp.eval(`document.getElementById('crew-continue-btn').click()`);await sleep(220);if(!await cdp.eval(`getComputedStyle(document.getElementById('tutorial-screen')).display!=='none'`))throw new Error('Tutorial did not open');await cdp.eval(`document.getElementById('tutorial-skip-btn').click()`);await sleep(350);
const buildInitial=await cdp.eval(`(()=>({visible:getComputedStyle(document.getElementById('build-ui')).display!=='none',cash:document.getElementById('build-budget').textContent,tier:document.getElementById('business-tier-name').textContent,capacity:document.getElementById('capacity-summary').textContent,upgradeDisabled:document.getElementById('upgrade-restaurant-btn').disabled,openDisabled:document.getElementById('open-restaurant-btn').disabled,lockedFixtures:document.querySelectorAll('#fixture-palette .fixture-btn.locked').length}))()`);
if(!buildInitial.visible||!buildInitial.openDisabled||buildInitial.lockedFixtures<3||!buildInitial.tier.includes('Starter Bistro')||!buildInitial.capacity.includes('2 active parties'))throw new Error(`Starter build limits failed: ${JSON.stringify(buildInitial)}`);

await cdp.eval(`document.getElementById('auto-layout-btn').click()`);await sleep(400);
const built=await cdp.eval(`(()=>({openDisabled:document.getElementById('open-restaurant-btn').disabled,req:[...document.querySelectorAll('#build-requirements .req')].map(x=>x.className),tables:window.__rkrGame.plan.filter(x=>x.key==='table').length,cash:window.__rkrGame.business.cash}))()`);
if(built.openDisabled||built.req.some(x=>!x.includes('ok'))||built.tables!==2||built.cash>=preflight.cash)throw new Error(`Compact starter layout failed: ${JSON.stringify(built)}`);

await cdp.eval(`document.getElementById('open-restaurant-btn').click()`);await sleep(1500);
const started=await cdp.eval(`(()=>({hud:getComputedStyle(document.getElementById('hud')).display!=='none',crew:document.querySelectorAll('#player-hud .player-chip').length,bots:document.querySelectorAll('#player-hud .player-chip.bot').length,timer:document.getElementById('timer').textContent,cash:document.getElementById('cash').textContent,sat:document.getElementById('satisfaction').textContent,growth:document.getElementById('growth-tier').textContent}))()`);
if(!started.hud||started.crew!==3||started.bots!==2||!started.timer||started.timer==='03:30'||started.growth!=='T1')throw new Error(`Service start failed: ${JSON.stringify(started)}`);

const fast=await cdp.eval(`(()=>{const g=window.__rkrGame;g.lives=2;const cash=g.business.cash,sat=g.business.satisfaction;g.completeTable({waitElapsed:5,patience:60,patienceMax:70,originalRecipes:['salad'],table:{id:0}},null,120);return{lives:g.lives,cashBefore:cash,cashAfter:g.business.cash,satBefore:sat,satAfter:g.business.satisfaction,fastServes:g.business.fastServes};})()`);
if(fast.lives!==3||fast.cashAfter<=fast.cashBefore||fast.satAfter<=fast.satBefore||fast.fastServes<1)throw new Error(`Fast-service reward failed: ${JSON.stringify(fast)}`);

if(cdp.exceptions.length)throw new Error(`Runtime exceptions detected: ${cdp.exceptions.join(' | ')}`);if(cdp.consoleErrors.length)throw new Error(`Console errors detected: ${cdp.consoleErrors.join(' | ')}`);
console.log('Progressive Growth V5 browser E2E passed:',JSON.stringify({preflight,crew,buildInitial,built,started,fast}));cdp.ws.close();
